<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barangay Income Disclosure</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <div class="container mt-5">
        <h1 class="text-center">Barangay Income Disclosure</h1>

        <!-- Chart Section -->
        <div class="chart-container">
            <canvas id="incomeChart" width="400" height="200"></canvas>
        </div>

        <!-- Development Fund Table -->
        <div class="mt-5">
            <h3 class="text-center">20% Development Fund</h3>
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th>Program 1</th>
                        <th>Program 2</th>
                        <th>Program 3</th>
                        <th>Program 4</th>
                        <th>Program 5</th>
                        <th>Program 6</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>&#8369;600,000.00</td>
                        <td>&#8369;500,000.00</td>
                        <td>&#8369;54,260.00</td>
                        <td>&#8369;90,000.00</td>
                        <td>&#8369;50,000.00</td>
                        <td>&#8369;90,000.00</td>
                        <td>&#8369;1,384,260.00</td>
                    </tr>
                    <tr>
                        <td>&#8369;251,625.00</td>
                        <td>&#8369;300,000.00</td>
                        <td>&#8369;54,260.00</td>
                        <td>&#8369;90,000.00</td>
                        <td>&#8369;50,000.00</td>
                        <td>&#8369;11,000.00</td>
                        <td>&#8369;756,885.00</td>
                    </tr>
                    <tr>
                        <td>&#8369;348,375.00</td>
                        <td>&#8369;200,000.00</td>
                        <td>&#8369;0.00</td>
                        <td>&#8369;0.00</td>
                        <td>&#8369;0.00</td>
                        <td>&#8369;79,000.00</td>
                        <td>&#8369;627,375.00</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Calendar and Upcoming Events Section -->
        <div class="row mt-5">
            <!-- Calendar -->
            <div class="col-md-6">
                <div class="calendar">
                    <h4 class="text-center" id="currentMonth"></h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>SU</th>
                                <th>MO</th>
                                <th>TU</th>
                                <th>WE</th>
                                <th>TH</th>
                                <th>FR</th>
                                <th>SA</th>
                            </tr>
                        </thead>
                        <tbody id="calendarBody">
                            <!-- Calendar will be generated by JavaScript -->
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Upcoming Events -->
            <div class="col-md-6">
                <div class="events">
                    <h4 class="text-center">Upcoming Events</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Activity</th>
                                <th>Amount</th>
                                <th>Fund</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Jan 5</td>
                                <td>Health Seminar</td>
                                <td>&#8369;15,000</td>
                                <td>Development</td>
                            </tr>
                            <!-- Add additional rows dynamically with PHP -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const ctx = document.getElementById('incomeChart').getContext('2d');
        const incomeChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [2019, 2020, 2021, 2022, 2023, 2024],
                datasets: [{
                        label: 'Official Receipt',
                        data: [400000, 450000, 500000, 480000, 530000, 550000],
                        borderColor: 'blue',
                        borderWidth: 2,
                    },
                    {
                        label: 'Cedula',
                        data: [200000, 220000, 250000, 240000, 260000, 270000],
                        borderColor: 'gray',
                        borderWidth: 2,
                    },
                ],
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                },
            },
        });

        // Generate Calendar
        function generateCalendar() {
            const calendarBody = document.getElementById('calendarBody');
            const currentMonth = document.getElementById('currentMonth');
            const date = new Date();
            const month = date.getMonth();
            const year = date.getFullYear();
            const firstDay = new Date(year, month, 1).getDay();
            const lastDate = new Date(year, month + 1, 0).getDate();
            const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

            currentMonth.textContent = `${monthNames[month]} ${year}`;

            let calendarHTML = '';
            let day = 1;

            for (let i = 0; i < 6; i++) {
                calendarHTML += '<tr>';
                for (let j = 0; j < 7; j++) {
                    if (i === 0 && j < firstDay) {
                        calendarHTML += '<td></td>';
                    } else if (day > lastDate) {
                        calendarHTML += '<td></td>';
                    } else {
                        const today = new Date();
                        const isToday = today.getDate() === day && today.getMonth() === month && today.getFullYear() === year;
                        calendarHTML += `<td${isToday ? ' class="bg-primary text-white"' : ''}>${day}</td>`;
                        day++;
                    }
                }
                calendarHTML += '</tr>';
            }

            calendarBody.innerHTML = calendarHTML;
        }

        document.addEventListener('DOMContentLoaded', generateCalendar);
    </script>
</body>

</html>